image: docker:cli
# Anchors  
.docker_login: &docker_login
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

.build_container_image:
  script:
    - *docker_login
    - cd $dir
    - docker pull $CI_REGISTRY_IMAGE/$image_name:latest || true
    - docker build --file ./$dockerfile --cache-from $CI_REGISTRY_IMAGE/$image_name:latest $docker_build_extra_args
      --tag $CI_REGISTRY_IMAGE/$image_name:$CI_COMMIT_SHORT_SHA
      --tag $CI_REGISTRY_IMAGE/$image_name:latest
      .
    - docker push $CI_REGISTRY_IMAGE/$image_name:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$image_name:latest

build:
  stage: build
  variables:
    image_name: blackbox-search
    dockerfile: docker/Dockerfile
    dir: .
  extends:
    - .build_container_image
